package com.predict_app.predictionservice.publishers;

import com.predict_app.predictionservice.dtos.events.PredictionRequestedEventDto;
import com.predict_app.predictionservice.dtos.events.ModelPredictRequestedEventDto;
import com.predict_app.predictionservice.dtos.events.PredictionCompletedCusomterEventDto;
import com.predict_app.predictionservice.dtos.events.PredictionCompletedAnalysticEventDto;

public interface PredictionEventPublisher {
    void publishCustomerProfileRequestedEvent(PredictionRequestedEventDto predictionRequestedEventDto);
    void publishModelPredictRequestedEvent(ModelPredictRequestedEventDto modelPredictRequestedEventDto);
    void publishPredictionCompletedEvent(PredictionCompletedCusomterEventDto predictionCompletedEventDto);
    void publishPredictionCompletedAnalyticsEvent(PredictionCompletedAnalysticEventDto predictionCompletedEventDto);
}
